---
services:
  influxdb:
    image: influxdb:2.1.1
    hostname: influxdb
    container_name: influxdb
    volumes:
      - ./influxdb-storage:/var/lib/influxdb2:rw
    env_file:
      - .env
    entrypoint: ["./entrypoint.sh"]
    restart: unless-stopped
    ports:
      - ${DOCKER_INFLUXDB_INIT_PORT}:8086
    networks:
      - grafana-monitoring

  telegraf:
    image: telegraf:1.19
    hostname: telegraf
    container_name: telegraf
    volumes:
      - ${TELEGRAF_CFG_PATH}:/etc/telegraf/telegraf.conf:rw
    env_file:
      - .env
    depends_on:
      - influxdb
    restart: unless-stopped
    networks:
      - grafana-monitoring

networks:
  grafana-monitoring:
    external: true
